import { defineNuxtModule, addTemplate, addPlugin, createResolver } from '@nuxt/kit';
export interface ApiProviderModuleOptions {
  baseURL: string;
  onErrorPath?: string;
  onSuccessPath?: string;
  /** path to module exporting default onRequest handler */
  onRequestPath?: string;
  /** Accepts "$api_provider" or "$api" or "api"; we inject without the "$" */
  provideName: string;
  defaultTimeoutMs?: number;
}

export default defineNuxtModule<ApiProviderModuleOptions>({
  meta: {
    name: 'nuxt-api-provider',
    configKey: 'apiProvider',
    compatibility: { nuxt: '>=4.0.0' },
  },
  defaults: {
    baseURL: '',
    provideName: '$apiProvider',
    defaultTimeoutMs: 20_000,
  },
  setup(moduleOptions, nuxt) {
    const resolver = createResolver(import.meta.url);

    const normalizedProvideName = moduleOptions.provideName?.startsWith('$')
      ? moduleOptions.provideName.slice(1)
      : moduleOptions.provideName || 'apiProvider';

    // 1) Config template
    addTemplate({
      filename: 'api-provider-config.mjs',
      getContents: () => {
        const cfg = {
          baseURL: moduleOptions.baseURL,
          defaultTimeoutMs: moduleOptions.defaultTimeoutMs ?? 20_000,
          provideName: normalizedProvideName,
        };
        return `export default ${JSON.stringify(cfg)}`;
      },
    });

    // 2) Handlers (error/success/request)
    addTemplate({
      filename: 'api-provider-handlers.mjs',
      getContents: () => {
        const imports: string[] = [];
        const fallbacks: string[] = [];

        if (moduleOptions.onErrorPath?.trim()) {
          imports.push(`export { default as onErrorHandler } from '${moduleOptions.onErrorPath}'`);
        } else {
          fallbacks.push(`export function onErrorHandler() {}`);
        }

        if (moduleOptions.onSuccessPath?.trim()) {
          imports.push(
            `export { default as onSuccessHandler } from '${moduleOptions.onSuccessPath}'`
          );
        } else {
          fallbacks.push(`export function onSuccessHandler() {}`);
        }

        if (moduleOptions.onRequestPath?.trim()) {
          imports.push(
            `export { default as onRequestHandler } from '${moduleOptions.onRequestPath}'`
          );
        } else {
          fallbacks.push(`
export async function onRequestHandler(ctx) {
  // ctx: { endpoint, options, queries, headers, baseURL }
  return ctx
}
`);
        }

        return `${imports.join('\n')}\n${fallbacks.join('\n')}`;
      },
    });

    // 3) Types
    addTemplate({
      filename: 'types/api-provider.d.ts',
      getContents: () => `
// Auto-generated by nuxt-api-provider
import type { IError, IOnRequestContext } from '${resolver.resolve('./runtime/api-utils')}'

declare module '#app' {
  interface NuxtApp {
    $${normalizedProvideName}: <T>(
      endpoint: string,
      options?: (RequestInit & { json?: unknown; timeoutMs?: number }) | null,
      queries?: Record<string, unknown>
    ) => Promise<T | undefined>
  }
}

declare module 'vue' {
  interface ComponentCustomProperties {
    $${normalizedProvideName}: <T>(
      endpoint: string,
      options?: (RequestInit & { json?: unknown; timeoutMs?: number }) | null,
      queries?: Record<string, unknown>
    ) => Promise<T | undefined>
  }
}

declare module '#build/api-provider-handlers.mjs' {
  export function onRequestHandler(ctx: IOnRequestContext): Promise<IOnRequestContext | void> | IOnRequestContext | void
  export function onErrorHandler(status: number, err: IError): Promise<void> | void
  export function onSuccessHandler<T = unknown>(endpoint: string, data: T | undefined): Promise<void> | void
}

export {}
`,
    });

    // 4) Plugin
    addPlugin({ mode: 'client', src: resolver.resolve('./runtime/plugin') });

    // 5) Include types
    nuxt.hook('prepare:types', ({ references }) => {
      references.push({ path: '#build/types/api-provider.d.ts' });
    });
  },
});
